on:
  push:
    branches:
      - main

jobs:
  verify:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm ci
      - run: npm test
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Collect coverage for client
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: client